name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: check workdir
      run: |
        pwd
    - name: should it be skipped?
      run: |
        # Get CommitMsg
        last_commit_log=$(git log -1 --pretty=format:"%s")
        echo "last commit log: $last_commit_log"

        feat="feat:[[:space:]].*$"
        fix="fix:[[:space:]].*$"
        test="test:[[:space:]].*$"
        chore="chore:[[:space:]].*$"
        merge="Merge pull request.*$"

        commit_msg_reg=(
          $feat
          $fix
          $test
          $chore
          $merge
        )

        check_commit_msg() {
          for regex in ${commit_msg_reg[*]}
            do
              echo "last commit log: $last_commit_log"
              echo "$regex"
              if [[ $last_commit_log =~ $regex ]]; then
                printf "do match \n\n  $last_commit_log  $regex"
                return 0
              else
                printf "does not match $last_commit_log  $regex"
              fi
            done
          return 1
        }

        check_commit_msg
        if [[ $? == 1 ]]
        then
          printf "\n\n $last_commit_log  commit message failed match"
          exit 1
        fi
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test --verbose
      env:
        CI: true
    - name: Deploy
      uses: sterlingwes/gh-pages-deploy-action@v1.1
      with:
        access-token: ${{secrets.deploy_key}}
        deploy-branch: gh-pages
        source-directory: docs
        build-command: npm install && npm run build
